import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {dailyTaskGuidance} from '../assets/daily-task-guidance-20261004.js';
import {backupPreview} from '../assets/progress-backup-preview-20261004.js';
const daily=[{id:'study-session',target:10,progress:2,title:'Latin foundation'},{id:'adaptive-focus',target:4,progress:1,focusTopic:'la-y8-stage-1',focusSubject:'latin',title:'Latin focus'},{id:'y8-mastery',target:25,progress:1,assignedTopic:'la-y8-stage-1',assignedSubject:'latin',title:'Practice + mastery'}];
assert.deepEqual(dailyTaskGuidance(daily[2],daily).shared,['Daily study total','Latin focus']);
assert.equal(dailyTaskGuidance(daily[2],daily).remaining,24);
assert.deepEqual(dailyTaskGuidance({...daily[2],assignedTopic:'fr-y8-different',assignedSubject:'french'},daily).shared,['Daily study total']);
assert.equal(dailyTaskGuidance({id:'latin-vocab',target:30,progress:5},daily).unit,'correct words');
const current={today:'2026-10-04',xp:14,daily};
const data=JSON.stringify({app:'lux-scholar-garden',state:{today:'2026-10-03',xp:100,daily:[{target:10,progress:10}]}});
assert.throws(()=>backupPreview('{}',current));
assert.equal(backupPreview(data,current).saved.done,1);
assert.equal(backupPreview(data,current).current.xp,14);
let imports=0,confirms=0,selectedRestore=null;
const elements=new Map();const document={getElementById:id=>{if(!elements.has(id))elements.set(id,{hidden:true,textContent:''});return elements.get(id)}};
const code=fs.readFileSync('assets/daily-progress-save.js','utf8');
const context=vm.createContext({backupPreview,document,Date,JSON,Number,selectedRestore,summary:()=>({done:0,total:3}),status(){},store:{getState:()=>({...current,importProgress:()=>{imports++;return{ok:true}}})},confirm:()=>{confirms++;return false},location:{reload(){throw Error('Preview must not reload')}}});
vm.runInContext(code.slice(code.indexOf('function previewRestore('),code.indexOf('function mount()')),context);
context.previewRestore(data,'Previous automatic copy',{savedAt:'2026-10-03T12:00:00Z'});
assert.equal(imports,0);assert.equal(confirms,0);
assert.equal(elements.get('daily-restore-preview').hidden,false);
assert.match(elements.get('daily-restore-description').textContent,/2026-10-03, 1\/1 tasks, 100 XP/);
context.previewRestore('{}','Invalid file');assert.equal(context.selectedRestore,null);assert.equal(elements.get('daily-restore-preview').hidden,true);
context.restore(data,'Previous copy');assert.equal(confirms,1);assert.equal(imports,0,'Cancelling restore preserves current progress');
const core=fs.readFileSync('assets/index-BLVOhKhN.core.js','utf8');assert.ok(core.includes('children:e=>(0,L.jsx)(LuxReadyRouter,{router:e})'));assert.ok(core.includes("document.documentElement.setAttribute('data-lux-ready','')"));
console.log('Remaining UX QA passed: topic-aware shared credit, remaining counts, validated restore previews without mutation, cancellation preserves progress and readiness gate is wired to committed router.');
const readinessCode=core.slice(core.indexOf('function LuxReadyRouter('),core.indexOf('var vD=ve();'));
let ready=false,callback,cleanup;
const readiness=vm.createContext({I:{useEffect:effect=>{cleanup=effect()}},L:{jsx:()=>null},oc(){},setTimeout:fn=>{callback=fn;return 1},clearTimeout(){},document:{documentElement:{setAttribute:()=>{ready=true}},body:{removeAttribute(){}}}});
vm.runInContext(readinessCode,readiness);readiness.LuxReadyRouter({router:{}});assert.equal(ready,false);callback();assert.equal(ready,true,'Ready gate opens without animation frames, including background tabs');assert.equal(typeof cleanup,'function');
// The header shows XP within a level, rather than total lifetime XP.
const wrapper=fs.readFileSync('assets/index-BLVOhKhN.js','utf8');
const gate=wrapper.slice(wrapper.indexOf(' const showLoadedProgress=()=>{'),wrapper.indexOf(' const observe=new MutationObserver(showLoadedProgress);'));
const levelCode=core.slice(core.indexOf('function bw('),core.indexOf('var Sw='));
for(const [total,header,expected] of [[14,'Lv 1 · 14 XPSearch',true],[122,'Lv 2 · 2 XPSearch',true],[122,'Lv 1 · 0 XPSearch',false],[122,'Lv 1 · 122 XPSearch',false],[300,'Lv 3 · 0 XPSearch',true]]){
 let shown=false;const ctx=vm.createContext({store:{getState:()=>({xp:total})},location:{pathname:'/study/biology/practise'},document:{documentElement:{hasAttribute:()=>false,setAttribute:()=>{shown=true}},querySelector:s=>s==='main'?{textContent:'Cell structure'}:{textContent:header}},getTopicCatalog:()=>[]});
 vm.runInContext(levelCode+';const scholarLevelProgress=xw;'+gate+';showLoadedProgress();',ctx);assert.equal(shown,expected,`Loading gate for ${total} total XP and ${header}`);
}
console.log('Loading gate regression passed: level 1 and level 2 rendered XP release the page; stale level/XP stay hidden.');
