import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {dailyTaskGuidance} from '../assets/daily-task-guidance-20261004.js';
import {backupPreview} from '../assets/progress-backup-preview-20261004.js';
const daily=[{id:'study-session',target:10,progress:2,title:'Latin foundation'},{id:'adaptive-focus',target:4,progress:1,focusTopic:'la-y8-stage-1',focusSubject:'latin',title:'Latin focus'},{id:'y8-mastery',target:25,progress:1,assignedTopic:'la-y8-stage-1',assignedSubject:'latin',title:'Practice + mastery'}];
assert.deepEqual(dailyTaskGuidance(daily[2],daily).shared,['Daily study total','Latin focus']);
assert.equal(dailyTaskGuidance(daily[2],daily).remaining,24);
assert.deepEqual(dailyTaskGuidance({...daily[2],assignedTopic:'fr-y8-different',assignedSubject:'french'},daily).shared,['Daily study total']);
assert.equal(dailyTaskGuidance({id:'latin-vocab',target:30,progress:5},daily).unit,'correct words');
const current={today:'2026-10-04',xp:14,daily};
const data=JSON.stringify({app:'lux-scholar-garden',state:{today:'2026-10-03',xp:100,daily:[{target:10,progress:10}]}});
assert.throws(()=>backupPreview('{}',current));
assert.equal(backupPreview(data,current).saved.done,1);
assert.equal(backupPreview(data,current).current.xp,14);
let imports=0,confirms=0,selectedRestore=null;
const elements=new Map();const document={getElementById:id=>{if(!elements.has(id))elements.set(id,{hidden:true,textContent:''});return elements.get(id)}};
const code=fs.readFileSync('assets/daily-progress-save.js','utf8');
const context=vm.createContext({backupPreview,document,Date,JSON,Number,selectedRestore,summary:()=>({done:0,total:3}),status(){},store:{getState:()=>({...current,importProgress:()=>{imports++;return{ok:true}}})},confirm:()=>{confirms++;return false},location:{reload(){throw Error('Preview must not reload')}}});
vm.runInContext(code.slice(code.indexOf('function previewRestore('),code.indexOf('function mount()')),context);
context.previewRestore(data,'Previous automatic copy',{savedAt:'2026-10-03T12:00:00Z'});
assert.equal(imports,0);assert.equal(confirms,0);
assert.equal(elements.get('daily-restore-preview').hidden,false);
assert.match(elements.get('daily-restore-description').textContent,/2026-10-03, 1\/1 tasks, 100 XP/);
context.previewRestore('{}','Invalid file');assert.equal(context.selectedRestore,null);assert.equal(elements.get('daily-restore-preview').hidden,true);
context.restore(data,'Previous copy');assert.equal(confirms,1);assert.equal(imports,0,'Cancelling restore preserves current progress');
const core=fs.readFileSync('assets/index-BLVOhKhN.core.js','utf8');assert.ok(core.includes('children:e=>(0,L.jsx)(LuxReadyRouter,{router:e})'));assert.ok(core.includes("document.documentElement.setAttribute('data-lux-ready','')"));
console.log('Remaining UX QA passed: topic-aware shared credit, remaining counts, validated restore previews without mutation, cancellation preserves progress and readiness gate is wired to committed router.');
